<a href="https://colab.research.google.com/github/zalak-joshi/Anima-l-Extinction/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/extinction_risk_dataset.csv")
df.head()

Species Name          Scientific Name  Current Population  \
0      Axolotl      Ambystoma mexicanum                1187   
1      Vaquita                Pholidota                2227   
2      Axolotl  Pseudoryx nghetinhensis                1305   
3      Axolotl                Pholidota                 927   
4        Saola       Podiceps gallardoi                4256   

   Population Decline Rate (%)  Habitat Loss (%)  Climate Threat Level (1-10)  \
0                        18.15             38.86                            2   
1                        13.09             18.70                            5   
2                        19.54             72.27                            2   
3                        21.02             39.29                            1   
4                        21.56             59.67                            6   

   Poaching Threat Level (1-10) Conservation Efforts  \
0                             4               Medium   
1                             9                  Low   
2                             3                  Low   
3                             7               Medium   
4                             5               Medium   

   Protected Area Coverage (%)  Extinction Probability (0-100%)  
0                         6.49                            20.87  
1                        33.31                            72.83  
2                        13.36                            46.25  
3                        63.31                            71.85  
4                        13.98                            93.19

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Species Name                     3000 non-null   object 
 1   Scientific Name                  3000 non-null   object 
 2   Current Population               3000 non-null   int64  
 3   Population Decline Rate (%)      3000 non-null   float64
 4   Habitat Loss (%)                 3000 non-null   float64
 5   Climate Threat Level (1-10)      3000 non-null   int64  
 6   Poaching Threat Level (1-10)     3000 non-null   int64  
 7   Conservation Efforts             3000 non-null   object 
 8   Protected Area Coverage (%)      3000 non-null   float64
 9   Extinction Probability (0-100%)  3000 non-null   float64
dtypes: float64(4), int64(3), object(3)
memory usage: 234.5+ KB


In [ ]:
df.isnull().sum()

Species Name                       0
Scientific Name                    0
Current Population                 0
Population Decline Rate (%)        0
Habitat Loss (%)                   0
Climate Threat Level (1-10)        0
Poaching Threat Level (1-10)       0
Conservation Efforts               0
Protected Area Coverage (%)        0
Extinction Probability (0-100%)    0
dtype: int64

In [ ]:
df.describe()

Current Population  Population Decline Rate (%)  Habitat Loss (%)  \
count         3000.000000                  3000.000000       3000.000000   
mean          2575.981000                    17.707063         49.978703   
std           1432.933707                     7.173890         23.016141   
min             10.000000                     5.000000         10.010000   
25%           1337.750000                    11.640000         30.227500   
50%           2627.000000                    17.825000         50.455000   
75%           3779.500000                    23.920000         69.805000   
max           4999.000000                    30.000000         89.980000   

       Climate Threat Level (1-10)  Poaching Threat Level (1-10)  \
count                  3000.000000                   3000.000000   
mean                      5.023667                      4.974000   
std                       2.566704                      2.555158   
min                       1.000000                      1.000000   
25%                       3.000000                      3.000000   
50%                       5.000000                      5.000000   
75%                       7.000000                      7.000000   
max                       9.000000                      9.000000   

       Protected Area Coverage (%)  Extinction Probability (0-100%)  
count                  3000.000000                      3000.000000  
mean                     42.600910                        60.025603  
std                      21.968312                        22.892984  
min                       5.020000                        20.010000  
25%                      23.557500                        39.905000  
50%                      42.535000                        60.580000  
75%                      61.980000                        80.100000  
max                      79.940000                        98.980000

In [ ]:
def extinct(x):
  if x > 90:
    return "Yes"
  elif x < 90 and x > 60:
    return "Possibly"
  else:
    return "No"
df["Extinct"] = df["Extinction Probability (0-100%)"].map(extinct)
df.head()

Species Name  Scientific Name  Current Population  \
0             1                0                1187   
1             8                5                2227   
2             1                7                1305   
3             1                5                 927   
4             7                6                4256   

   Population Decline Rate (%)  Habitat Loss (%)  Climate Threat Level (1-10)  \
0                        18.15             38.86                            2   
1                        13.09             18.70                            5   
2                        19.54             72.27                            2   
3                        21.02             39.29                            1   
4                        21.56             59.67                            6   

   Poaching Threat Level (1-10)  Conservation Efforts  \
0                             4                     2   
1                             9                     1   
2                             3                     1   
3                             7                     2   
4                             5                     2   

   Protected Area Coverage (%)  Extinction Probability (0-100%)   Extinct  
0                         6.49                            20.87        No  
1                        33.31                            72.83  Possibly  
2                        13.36                            46.25        No  
3                        63.31                            71.85  Possibly  
4                        13.98                            93.19       Yes

In [ ]:
from sklearn.preprocessing import LabelEncoder
for i in ["Species Name", "Scientific Name", "Conservation Efforts", "Extinct"]:
  label_encoder = LabelEncoder()
  df[i] = label_encoder.fit_transform(df[i])

In [ ]:
df.head()

Species Name  Scientific Name  Current Population  \
0             1                0                1187   
1             8                5                2227   
2             1                7                1305   
3             1                5                 927   
4             7                6                4256   

   Population Decline Rate (%)  Habitat Loss (%)  Climate Threat Level (1-10)  \
0                        18.15             38.86                            2   
1                        13.09             18.70                            5   
2                        19.54             72.27                            2   
3                        21.02             39.29                            1   
4                        21.56             59.67                            6   

   Poaching Threat Level (1-10)  Conservation Efforts  \
0                             4                     2   
1                             9                     1   
2                             3                     1   
3                             7                     2   
4                             5                     2   

   Protected Area Coverage (%)  Extinction Probability (0-100%)  Extinct  
0                         6.49                            20.87        0  
1                        33.31                            72.83        1  
2                        13.36                            46.25        0  
3                        63.31                            71.85        1  
4                        13.98                            93.19        2

In [ ]:
from sklearn.model_selection import train_test_split
x = df.iloc[:, 0:10]
y = df["Extinct"]

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)


In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)

LogisticRegression()

In [ ]:
ypred = model.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(ytest, ypred)
conf_matrix = confusion_matrix(ytest, ypred)
class_report = classification_report(ytest, ypred)

# Print results
print("Model Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Model Accuracy: 0.9816666666666667
Confusion Matrix:
 [[290   4   0]
 [  3 228   3]
 [  0   1  71]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       294
           1       0.98      0.97      0.98       234
           2       0.96      0.99      0.97        72

    accuracy                           0.98       600
   macro avg       0.98      0.98      0.98       600
weighted avg       0.98      0.98      0.98       600

